import { DollarSign, FileDown, Table as TableIcon } from "lucide-react";
import { XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line, PieChart, Pie, Cell } from "recharts";
import { Button } from "@/components/ui/button";
import { generatePDF } from "@/lib/pdfGenerator";
import * as Xlsx from "xlsx";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { DashboardStats } from "@/types";
import { useCurrency } from "@/contexts/CurrencyContext";
import { useCompany } from "@/contexts/CompanyContext"; // Assuming this context exists based on previous file content
import StatCard from "@/components/StatCard"; // Assuming this component exists

const monthlyData = [
  { month: "Aug", revenue: 38000, projects: 12 },
  { month: "Sep", revenue: 42000, projects: 15 },
  { month: "Oct", revenue: 35000, projects: 10 },
  { month: "Nov", revenue: 50000, projects: 18 },
  { month: "Dec", revenue: 46000, projects: 14 },
  { month: "Jan", revenue: 55000, projects: 20 },
  { month: "Feb", revenue: 52000, projects: 17 },
];

const serviceBreakdown = [
  { name: "Branding", value: 35, color: "hsl(234, 85%, 60%)" },
  { name: "Print", value: 28, color: "hsl(152, 60%, 45%)" },
  { name: "Digital Design", value: 22, color: "hsl(38, 92%, 55%)" },
  { name: "Packaging", value: 15, color: "hsl(280, 65%, 55%)" },
];

export default function Reports() {
  const { formatAmount, currency } = useCurrency();
  const { companyDetails } = useCompany();
  const [stats, setStats] = useState<DashboardStats | null>(null);

  useEffect(() => {
    fetchStats();
  }, []);

  const fetchStats = async () => {
    try {
      const data = await api.dashboard.stats();
      setStats(data);
    } catch (error) {
      console.error("Failed to fetch dashboard stats", error);
    }
  };

  const handleExportPDF = () => {
    if (!stats) return;

    // Create a simplified data structure for the PDF table since we don't have monthly data from API yet
    // For now, we'll use the stats as a summary
    const reportData = [
      { category: "Revenue", value: formatAmount(stats.revenue) },
      { category: "Expenses", value: formatAmount(stats.expenses) },
      { category: "Net Income", value: formatAmount(stats.netIncome) },
      { category: "Outstanding Invoices", value: formatAmount(stats.unpaidAmount) },
      { category: "Pending Quotations", value: stats.pendingQuotations.toString() }
    ];

    generatePDF({
      title: "BUSINESS PERFORMANCE REPORT",
      filename: "financial_report",
      companyDetails,
      data: reportData,
      columns: [
        { header: "Category", dataKey: "category" },
        { header: "Value", dataKey: "value" },
      ],
      totals: [
        { label: "Net Income:", value: formatAmount(stats.netIncome) }
      ],
      footerNote: "Generated by BrandFlow Suite - Internal Use Only"
    });
  };

  const handleExportExcel = () => {
    if (!stats) return;
    const wb = Xlsx.utils.book_new();

    // Financial Sheet
    const financialData = [
      { Metric: "Total Revenue", Value: stats.revenue },
      { Metric: "Total Expenses", Value: stats.expenses },
      { Metric: "Net Income", Value: stats.netIncome },
      { Metric: "Unpaid Invoices", Value: stats.unpaidAmount },
      { Metric: "Pending Quotations", Value: stats.pendingQuotations },
    ];
    const revenueWs = Xlsx.utils.json_to_sheet(financialData);
    Xlsx.utils.book_append_sheet(wb, revenueWs, "Financial Overview");

    Xlsx.writeFile(wb, "financial_report.xlsx");
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Reports & Analytics</h1>
          <p className="text-muted-foreground text-sm mt-1">Business performance insights</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" className="gap-2" onClick={handleExportPDF} disabled={!stats}>
            <FileDown className="h-4 w-4" /> Export PDF
          </Button>
          <Button variant="outline" className="gap-2" onClick={handleExportExcel} disabled={!stats}>
            <TableIcon className="h-4 w-4" /> Export Excel
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard
          title="Total Revenue"
          value={stats ? formatAmount(stats.revenue) : "..."}
          change=""
          trend="neutral"
          icon={DollarSign}
        />
        <StatCard
          title="Total Expenses"
          value={stats ? formatAmount(stats.expenses) : "..."}
          change=""
          trend="neutral"
          icon={DollarSign}
        />
        <StatCard
          title="Net Income"
          value={stats ? formatAmount(stats.netIncome) : "..."}
          change=""
          trend={stats && stats.netIncome >= 0 ? "up" : "down"}
          icon={DollarSign}
        />
        <StatCard
          title="Pending Quotations"
          value={stats ? stats.pendingQuotations.toString() : "..."}
          change=""
          trend="neutral"
          icon={FileDown}
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <div className="lg:col-span-2 rounded-xl bg-card border border-border p-5 animate-fade-in">
          <h3 className="font-semibold mb-1">Revenue Trend</h3>
          <p className="text-sm text-muted-foreground mb-6">Last 7 months performance (Mock Data)</p>
          <ResponsiveContainer width="100%" height={280}>
            <LineChart data={monthlyData}>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(228,15%,90%)" vertical={false} />
              <XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fontSize: 12 }} />
              <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12 }} tickFormatter={(v) => `${currency.symbol}${v / 1000}k`} />
              <Tooltip contentStyle={{ borderRadius: 12, border: "1px solid hsl(228,15%,90%)" }} formatter={(value: number) => [formatAmount(value), "Revenue"]} />
              <Line type="monotone" dataKey="revenue" stroke="hsl(234, 85%, 60%)" strokeWidth={2.5} dot={{ r: 4, fill: "hsl(234, 85%, 60%)" }} />
            </LineChart>
          </ResponsiveContainer>
        </div>

        <div className="rounded-xl bg-card border border-border p-5 animate-fade-in">
          <h3 className="font-semibold mb-1">Services Breakdown</h3>
          <p className="text-sm text-muted-foreground mb-4">Revenue by service type (Mock Data)</p>
          <ResponsiveContainer width="100%" height={180}>
            <PieChart>
              <Pie data={serviceBreakdown} cx="50%" cy="50%" innerRadius={50} outerRadius={75} paddingAngle={3} dataKey="value">
                {serviceBreakdown.map((entry, i) => (
                  <Cell key={i} fill={entry.color} />
                ))}
              </Pie>
              <Tooltip />
            </PieChart>
          </ResponsiveContainer>
          <div className="space-y-2 mt-2">
            {serviceBreakdown.map((s) => (
              <div key={s.name} className="flex items-center justify-between text-sm">
                <div className="flex items-center gap-2">
                  <div className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: s.color }} />
                  <span>{s.name}</span>
                </div>
                <span className="font-semibold">{s.value}%</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
